apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefile-secret
    secretNamespace: terraform
    shareName: nexus
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl