apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nexus.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 15Gi